inherit_gem:
  rubocop-discourse: stree-compat.yml
AllCops:
  Exclude:
    - vendor/**/*
    - gems/**/*
    - bin/rspec
Style/Copyright:
  Notice: |-
    ^SPDX-License-Identifier: Apache-2\.0
    SPDX-FileCopyrightText: 2\d{3} .+
  AutocorrectNotice: |
    # SPDX-License-Identifier: Apache-2.0
    # SPDX-FileCopyrightText: 2026 Michiel Hendriks